#!/bin/bash
export DJANGO_SETTINGS_MODULE=webserver.settings
mkdir -p /tmp/django_media_root/tasa
export DATA_FOLDER=/tmp/django_media_root
if [ $PORT ];
   then
       PYTHON='.conda/bin/python'
       APP_PORT=$PORT
       echo 'Using python:'$PYTHON
   else
       PYTHON=`which python`
       APP_PORT=8081
       echo 'Using python:'$PYTHON
fi

#Install TASA
$PYTHON setup.py build
$PYTHON setup.py install

#Collect static files (images, javascripts etc)
$PYTHON  webserver/manage.py collectstatic --noinput

#Start the webserver
$PYTHON webserver/manage.py runserver 0.0.0.0:$APP_PORT
