#!/bin/bash
export DJANGO_SETTINGS_MODULE=webserver.settings
if [ $HOME];
   then
       mkdir -p $HOME/django_media_root/tasa
       export DATA_FOLDER=$HOME/django_media_root
   else
       rm -rf /tmp/tasa_assets/django_media_root
       mkdir -p /tmp/tasa_assets/django_media_root/tasa
       export DATA_FOLDER=/tmp/tasa_assets/django_media_root
fi

if [ $PORT ];
   then
       PYTHON='.conda/bin/python'
       echo 'Using python:'$PYTHON
   else
       PYTHON=`which python`
       PORT=8081
       echo 'Using python:'$PYTHON
fi

#Install TASA
$PYTHON setup.py build
$PYTHON setup.py install

#Collect static files (images, javascripts etc)
$PYTHON  webserver/manage.py collectstatic --noinput

#Start the webserver
$PYTHON webserver/manage.py runserver 0.0.0.0:$PORT
