#!/bin/bash
export DJANGO_SETTINGS_MODULE=webserver.settings
mkdir -p /tmp/django_media_root/tasa
export DATA_FOLDER=/tmp/django_media_root
.conda/bin/python setup.py build
.conda/bin/python setup.py install
#Collect static files (images, javascripts etc)
.conda/bin/python webserver/manage.py collectstatic --noinput
#Start the webserver
.conda/bin/python webserver/manage.py runserver 0.0.0.0:$VCAP_APP_PORT
